### PR TITLE
Create Docker image

### PR DESCRIPTION
**Pull request by srueg**
Set up a Dockerfile and entrypoint script to build a Docker image.

Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. It does not make sense to run this in Docker, as it's intended to be used as a java agent.

**Comment by srueg** [comment]
I am actually running it in Kubernetes as a side car, using the http server mode.

**Comment by brian-brazil** [comment]
I'd suggest using the java agent then.

**Comment by srueg** [comment]
Unfortunately that's not possible as I don't control the other image and it doesn't contain the agent.

**Comment by srueg** [comment]
I might have found a possible solution though: https://github.com/banzaicloud/prometheus-jmx-exporter-operator

**Comment by srueg** [comment]
Unfortunately the JMX operator doesn't work as expected and it makes some assumptions about the targeted environment we can't fulfill.

So I have a valid use case to run the JMX exporter in a Docker image. There are also several other images which package it, but they're all outdated and I think it would make most sense to have the Dockerfile in this project. How do you feel about this?

**Comment by brian-brazil** [comment]
I continue to believe that the agent is the best way to do things.

**Pull request closed without merging**
