### PR TITLE
Added more documentation to README

### PR DESCRIPTION
**Pull request by davidmpaz**
Hi,

could we please add this to main stream, for dummies like me? In my case it was not straight clear what to do in order to get things up and running. I think this could contribute to newbies to get onboard better.

Thanks and cheers.
David

-----

Changes:

Added suggestions on running the agent when getting Exceptions:

io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect JMX scrape failed:
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NoInitialContextException:
Can not instantiate class: org.apache.naming.java.javaURLContextFactory

Added more steps to use it as http server.

### CODE REVIEW

**Comment by dhoard** [comment]
@davidmpaz Updating the README makes sense, but I don't feel we should reference a GitHub issue in the documentation.

**Comment by davidmpaz** [comment]
> @davidmpaz Updating the README makes sense, but I don't feel we should reference a GitHub issue in the documentation.

Should i update the Pull Request ?

**Comment by dhoard** [comment]
> Should i update the Pull Request ?

Please. Here is what I would suggest... something like https://github.com/dhoard/jmx_exporter/tree/update-readme

**Comment by davidmpaz** [comment]
I am fine with that. Just one small suggestion please. I think it is still usefull to tell explicitly it is needed to build the project to get a http server release in place, that or include it in the downloadable artifacts alonside with the agent :)

Besides that we can close this PR right away.

Thanks for your time on this,
cheers,
David

**Comment by dhoard** [comment]
@davidmpaz the HTTP server is embedded in the agent jar.

**Comment by davidmpaz** [comment]
oh, good to know :) it was not obvious for me at start. Thanks! 😅

**Comment by fstab** [comment]
Thanks a lot. @dhoard please create a PR out of your branch.

BTW this ticket got me thinking we should terminate with an error if `jmx_exporter` is started as an agent but `jmxUrl` or `hostPort` is configured. I created #673 for that. Let me know if I'm missing a valid scenario where you want this.

**Pull request closed without merging**
