### PR TITLE
Add metrics quota kafka for client-id or/and user

### PR DESCRIPTION
**Pull request by alvarobacelar**
@brian-brazil adding metrics for quotas of client-id and/or user for Apache Kafka config exemples. This patter alredy is working in my environment. However this is metrics only appears when the quotas they are enebled. 

Link of documentation:
https://kafka.apache.org/documentation/#remote_jmx

### CODE REVIEW

**Comment by brian-brazil** [comment]
What do the resultant metrics look like?

**Comment by alvarobacelar** [comment]
This is metrics pickup two pattern **kafka.server:type={Produce|Fetch}...** and **kafka.server:type=Request** the first show two attributes: _throttle-time_ (indicates the amount of time in ms the client was throttled) and _byte-rate_ (indicates the data produce/consume rate of the client in bytes/sec). The second show two attributes also: _throttle-time_ (indicates the amount of time in ms the client was throttled) and _request-time_ (indicates the percentage of time spent in broker network and I/O threads to process requests from client group).

The altering the PR show the metrics this way:
1. When user isn't available:
```
- pattern: kafka.server<type=(.+), client-id=(.+)><>([^:]+)
  name: kafka_server_$1_$3
  type: GAUGE
  labels:
    clientId: "$2"
```
kafka_server_Fetch_throttle_time{clientId="name-client-consumer"}
kafka_server_Fetch_byte_rate{clientId="name-client-consumer"}
kafka_server_Produce_throttle_time{clientId="name-client-produce"}
kafka_server_Produce_byte_rate{clientId="name-client-producer"}
kafka_server_Request_request_time{clientId="name-client-producer-or-consumer"}
kafka_server_Request_throttle_time{clientId="name-client-producer-or-consumer"}

1. When user is available
```
- pattern: kafka.server<type=(.+), user=(.+), client-id=(.+)><>([^:]+)
  name: kafka_server_$1_$4
  type: GAUGE
  labels:
    user: "$2"
    clientId: "$3" 

```
kafka_server_Fetch_throttle_time{user="client-user",clientId="name-client-consumer"}
kafka_server_Fetch_byte_rate{user="client-user",clientId="name-client-consumer"}
kafka_server_Produce_throttle_time{user="client-user",clientId="name-client-produce"}
kafka_server_Produce_byte_rate{user="client-user",clientId="name-client-producer"}
kafka_server_Request_request_time{user="client-user",clientId="name-client-producer-or-consumer"}
kafka_server_Request_throttle_time{user="client-user",clientId="name-client-producer-or-consumer"}

**Comment by brian-brazil** [comment]
The type there looks like it should be a label

**Comment by alvarobacelar** [comment]
Brian, the label is the client and/or user then use quota. The type is request, produce and fetch, each type have one or many clients and/or user.

**Comment by brian-brazil** [comment]
I understand, type still looks like it should also be a label.

**Comment by alvarobacelar** [comment]
Ok, I'm going to change this and request new PR.

**Comment by alvarobacelar** [comment]
@brian-brazil I changed the type of metrics for label. Really got better for to filter in the Grafana, por exemple.

**Comment by brian-brazil** [comment]
Is there a better label name than type for this? Maybe resource or call?

**Comment by alvarobacelar** [comment]
@brian-brazil resource is better, I changed it.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by itsmjeu** [comment]
kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count is correct? 

I get so high values on it how can I fix it?

**Comment by makeloffve** [comment]
> kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count is correct?
> 
> I get so high values on it how can I fix it?
> 
> Element	Value
> {instance="host1:7071",job="kafka-prod"}	974617168.167857
> {instance="host2:7071",job="kafka-prod"}	976948542.4892857
> {instance="host3:7071",job="kafka-prod"}	975653126.6785713
> {instance="host4:7071",job="kafka-prod"}	972956459.8928571
> {instance="host5:7071",job="kafka-prod"}	980170441.1214286

@alvarobacelar Is there a plan to fix it ?

**Comment by alvarobacelar** [comment]
Hello @makeloffve. 
This metrics is a counter, you must use function rate() to get value on prometheus/grafana.
In my case, these metrics work for me this way on Grafana: 
```
rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{job=\"$job\",instance=~\"$broker\"}[1m]) / 10000000
```
The regex that might get this metrics is the line bellow:
https://github.com/prometheus/jmx_exporter/blob/add7897f513f3981f91f013cd7f3617a532c7b79/example_configs/kafka-2_0_0.yml#L96
If we put in this regex to get another attributes, like MeanRate, the regex will get a lot of others metrics and the /metrics will be very large and the consequence, the prometheus' scrap will take a long time when you to have a many topics in your cluster.

I recommend that you use this query above. 

I uploaded a dashboard for this exporter file in the grafana:
https://grafana.com/grafana/dashboards/11962

**Pull request merged**
