### PR TITLE
Allow java agent to bind to specific IP/hostname

### PR DESCRIPTION
**Pull request by icetrain**

### CODE REVIEW

**Comment by icetrain** [comment]
Solves #79 if it's acceptable to specify address instead of interface name.

**Comment by brian-brazil** [comment]
This seems fine. I'm a little worried that if there's ever additional parameters that it'll be tricky to add them syntactically. What do you think?

**Comment by icetrain** [comment]
I choose this solution to not break existing configurations but I agree that the current parameter syntax will make future changes tricky. It would probably be a good idea to migrate to something like comma separated key/values or system properties at some point.

**Comment by brian-brazil** [comment]
Let's figure it out when it comes up.

**Pull request merged**
