### PR TITLE
Remove the use of the default, static CollectorRegistry

### PR DESCRIPTION
**Pull request by jkimixl**
It looks like #498 can be resolved with this simple change so that the CollectorRegistrys from multiple JavaAgents don't interfere with each other.  The change in the WebServer isn't strictly necessary, I think, but done to keep things parallel.

Submitted for your consideration.

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'm not sure we should be complicating things like this, exporters should only use custom registries in very specific circumstances which don't apply to the jmx exporter.

**Comment by jkimixl** [comment]
Maybe it doesn't factor into the WebServer as much, but the JavaAgent's CollectorRegistry.defaultRegistry is already not the "default" one in the sense that it's at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry rather than io.prometheus.client.CollectorRegistry.

I haven't tried, but I assume if you started the WebServer with a JavaAgent attached, the two registries will happily ignore each other.  Having a single CollectorRegistry per exporter seems like a perfectly good rule of thumb.  I don't know what specific circumstances you're thinking of, but JavaAgent already seems to be using a custom registry.

**Comment by brian-brazil** [comment]
The java agent uses the default registry, that shading subsequently happens is orthogonal.

**Comment by jkimixl** [comment]
Updated the PR to reflect my understanding of the best implementation of this change possible.
 
I can't believe I'm the first one to want different polling intervals for vm-level info as the application-level info.  That seems so useful to me, and the cost seems so minimal.

**Comment by brian-brazil** [comment]
I believe you are the first, and I'm not at all convinced that it's wise to allow users to over-engineer their monitoring like this.

**Comment by brian-brazil** [comment]
Per above I don't think this makes sense. If you really need this you can always do additional shading.

**Pull request closed without merging**
