### PR TITLE
Docker Image for HTTP exporter

### PR DESCRIPTION
**Pull request by amimimor**
I've created a dir named 'docker' that contains the necessary files to build and run a Docker container of the http exporter. If the PR is of interest, I would happily add docs on the correct 'docker build ...' cmd as well as the 'docker run ...' cmd as I've already outlined in [my docker hub repo](https://hub.docker.com/r/amimimor/jmx-prometheus/). Currently the image is hosted on my docker hub account. If you'd like I can change the builder to create the image under a different account (prometheus?)

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for sharing. This exporter is intended to be primarily run as a Java agent, so a Docker image doesn't help much towards that as everyone would have to create their own.

**Comment by amimimor** [comment]
Hi Brian and thanks for the reply.
The Docker image doesn't need to be created by anybody - I just added the way to do that if someone want to modify the sources and recreate the image.
The image can be consumed as it is.
The 'docker run ...' defines custom params such as to which port the process should bind, etc. but besides that, the user only has to create a certain config.yml (as with the javaagent or http server)

On 12 Jul 2017, at 22:37, Brian Brazil <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for sharing. This exporter is intended to be primarily run as a Java agent, so a Docker image doesn't help much towards that as everyone would have to create their own.

**Comment by brian-brazil** [comment]
That doesn't help with running an agent, as the jar would need to be added into the application's docker image.

**Comment by amimimor** [comment]
Agreed.
But that is exactly why I created the Image, because using the javaagent seemed to me as a too 'involved' mechanism exposing processes which are not my own.
For example, I needed the exporter to be exporting Kafka JMX metrics.
Our Kafka is dockerized. I didn't think it would be a too good idea to 'fork' the wurstmeister/kafka image, then to edit its start script so that it would be wrapped by the javaagent.
However, just 'side kicking' the exporter container and pointing it to the Kafka container was quite easy and not 'involved' at all.

Anyways. This is OSS. I totally get that my goals do not align with the projects' goals so no hard feelings if it gets rejected.
Cheers,
Amit M.
On 12 Jul 2017, at 22:43, Brian Brazil <notifications@github.com<mailto:notifications@github.com>> wrote:


That doesn't help with running an agent, as the jar would need to be added into the application's docker image.

**Comment by brian-brazil** [comment]
We generally try to encourage the java agent (for example another user recently discovered that the http server form combined with a kafka with many many partitions doesn't end well), and using official builds so a Docker image like this isn't something I'm aiming for right now.

**Comment by amimimor** [comment]
Cool. Is there any license violation or any principle/personal objection with me keeping the Docker image publicly available in my docker hub repo?
It is, btw, tagged with the official mvn version (0.10.0-SNAPSHOT) if I recall.


On 12 Jul 2017, at 22:54, Brian Brazil <notifications@github.com<mailto:notifications@github.com>> wrote:


We generally try to encourage the java agent (for example another user recently discovered that the http server form combined with a kafka with many many partitions doesn't end well), and using official builds so a Docker image like this isn't something I'm aiming for right now.

**Comment by brian-brazil** [comment]
This is all Apache 2.0, there's no problems there.

**Comment by agolomoodysaada** [comment]
@brian-brazil since you seem to be referring to me here https://github.com/prometheus/jmx_exporter/issues/159

> for example another user recently discovered that the http server form combined with a kafka with many many partitions doesn't end well

I'd like to mention that my issue was resolved and mainly due to me using the exporter from laptop against a remote JMX endpoint. By running the same docker container on the remote machine side-by-side the Kafka process, everything worked significantly better.

**Comment by r4j4h** [comment]
Can also confirm that running it in a sidecar worked for us. We used it for the same reasons as @amimimor in a Kubernetes environment for metrics scraping. The only interesting thing we encountered with this approach wasn't performance related but was the fact that the jmx exporter http server serves its own jmx metrics as well :)

Should point out that according to our memory usage metrics those sidecars seem to average ~90MB of RAM though, so it's likely more efficient to have them combined.

**Comment by brian-brazil** [comment]
> The only interesting thing we encountered with this approach wasn't performance related but was the fact that the jmx exporter http server serves its own jmx metrics as well :)

No it doesn't, that'd cause confusion.

> Should point out that according to our memory usage metrics those sidecars seem to average ~90MB of RAM though, so it's likely more efficient to have them combined.

The Prometheus architecture is not to have such "uberagents" as they're harder to manage.

**Comment by amimimor** [comment]
Let me just add that since we are microserviced, and using Docker, managing anything is an issue. Gladly it is not ours since we let cluster managers such as Kubernetes to do that, therefore a few uberagents around is not an issue at all, at least for us.

On 19 Jul 2017, at 9:31, Brian Brazil <notifications@github.com<mailto:notifications@github.com>> wrote:


The only interesting thing we encountered with this approach wasn't performance related but was the fact that the jmx exporter http server serves its own jmx metrics as well :)

No it doesn't, that'd cause confusion.

Should point out that according to our memory usage metrics those sidecars seem to average ~90MB of RAM though, so it's likely more efficient to have them combined.

The Prometheus architecture is not to have such "uberagents" as they're harder to manage.

**Comment by brian-brazil** [comment]
You misunderstand the management issues with uberagents. Docker and Kubernetes do not make a difference, see https://www.robustperception.io/one-agent-to-rule-them-all/

**Comment by eedugon** [comment]
@amimimor , @r4j4h , @agolomoodysaada : I agree with your view, and I don't know if we are really missing something or the real benefits of running the exporter as a javaagent. For us the javaagent implies changes in the main java service, and we prefer to scrape the mbeans from the outside (as a sidecar in a k8s pod for example).

Anyway, I have written a Dockerfile + start.sh to create a jmx-exporter http docker with the following features:

- Automatic Configuration: config.xml creation based on environment variables and templates.

- Static Configuration: if a config.xml is mapped into /opt/jmx_exporter/config/, then environment variables won't be considered, and the provided configuration will be used (static).

- Flexible rules: via environment variables we can select the rules to apply to the configuration (only if Automatic Configuration feature is used and only 1 rules file allowed).

- check_init : With check init enabled (by default is disabled), jmx_exporter will wait until the remote jmx port is available (this feature uses nagios check_jmx plugin) before starting the exporter itself.

Check it out if you want: https://github.com/eedugon/jmx-exporter-dockerized

@brian-brazil : I assume that you don't, but if you ever consider it useful don't hesitate on reusing the code or asking me to share it.

Regards,
   Eduardo

**Comment by balboah** [comment]
I can also add that I'm successfully using it as a sidecar in kubernetes instead of building a custom image with an agent baked in, basically same as @eedugon. Wanted to see if submitting a PR would be accepted but I guess not after finding this issue :)

**Comment by tmc** [comment]
Just another peep that having this available as an addon container in k8s would be useful.

**Pull request closed without merging**
