### PR TITLE
health endpoint

### PR DESCRIPTION
**Pull request by f1yegor**
just health endpoint to check that jmx_exporter is working.
because jmx_exporter now has no cache, it's heavy to use /metrics for this.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why do you want to add this? This result is not valid with that content type.

**Comment by f1yegor** [comment]
Fixed content type.
Some services monitor health status of exporter.

**Comment by brian-brazil** [comment]
Which services are these? Prometheus only uses /metrics to determine health.
We don't currently offer this sort of endpoint on any of our exporters, so if we're adding it we should be consistent across all services.

I'm hesitant to accept a way that has two different ways of indicating health (content and status code) as I've seen that get confusing in the past.

**Comment by f1yegor** [comment]
I use mesos to manage exporter with health check. Unfortunately mesos provides only GET http requests for health, which is high-consuming for exporter.

**Comment by brian-brazil** [comment]
Last time I checked mesos doesn't support health checks. Which scheduler are you using? Aurora at least is quite flexible in this regard, as I made it generic about a year ago.

**Comment by f1yegor** [comment]
marathon

**Comment by brian-brazil** [comment]
Have you considered running this as an agent rather than a http server? That's the recommended way to do things, as it avoids management hassle like this and gives you better metrics.

**Comment by f1yegor** [comment]
From my point of view agent way is not so straightforward, because it's hard to figure out how to deal with different frameworks. Somebody already described how to do it for kafka-mesos, and it's not easy.

**Comment by brian-brazil** [comment]
If adding a command line argument to one of your applications is difficult, I'd suggest working on it until it isn't. That's a fundamental operational ability that you shouldn't have to think about.

**Comment by josdotso** [comment]
Would like to see this happen for use in Kubernetes liveness and readiness probes.

**Pull request closed without merging**
