### PR TITLE
Issue 98 : Support configuring host address for WebServer exporter setup

### PR DESCRIPTION
**Pull request by marcelmay**
Implements configuring host, including small test.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for the PR, this code should be the same as what's already in the agent.

**Comment by marcelmay** [comment]
@brian-brazil , thx for the fast feedback.

Would you prefer to move the method into shared collector module, as a shared helper class (used by agent and webserver)?

Or should I duplicate the code from agent (and remove the small test, too)?

**Comment by brian-brazil** [comment]
The code is fairly simple, so I think copying it is okay.

**Comment by marcelmay** [comment]
Updated pull request, now WebServer configures hostname like JavaAgent

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
