### PR TITLE
Fixed regex the metrics of kafka client

### PR DESCRIPTION
**Pull request by alvarobacelar**
@brian-brazil. I fixed the regexs the patterns of kafka consumer and producer (clients) created by Saada.

The Metrics of consumer, for exemple, appear like this: 
https://gist.githubusercontent.com/alvarobacelar/a5cc687b72f86b9291f4efb88cd8f4c3/raw/e0abeb582e7282e7c2c978b86698b2cf09d18670/metric-consumer

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain what's wrong with the existing config?

I'd prefer not to have the kafka client here, applications should handle that themselves.

**Comment by alvarobacelar** [comment]
Before, this pattern below captured everything after clien-id and was added in label clientId: 

```
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+)><>([a-z-]+)
    name: kafka_$1_$2_$4
    labels:
      clientId: "$3"
    help: "Kafka client JMX metric $1 $2"
    type: GAUGE
```

I Added another pattern that captured and add in the label correct.
```
 - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+), partition=(.+)><>([a-z-]+)
    name: kafka_$1_$2_$6
    labels:
      clientId: "$3"
      topic: "$4"
      partition: "$5"
    help: "Kafka client JMX metric $1 $2"
    type: GAUGE
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+)><>([a-z-]+)
    name: kafka_$1_$2_$5
    labels:
      clientId: "$3"
      topic: "$4"
    help: "Kafka client JMX metric $1 $2"
    type: GAUGE
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), node-id=(.+)><>([a-z-]+)
    name: kafka_$1_$2_$5
    labels:
      clientId: "$3"
      nodeId: "$4"
    help: "Kafka client JMX metric $1 $2"
    type: GAUGE
``` 

I understand you don't want have kafka clients here, but in the ecosistem Apache Kafka is very important to monitory end-to-end the peaces mainly the clients.

**Comment by brian-brazil** [comment]
> Before, this pattern below captured everything after clien-id and was added in label clientId:

There's something off here, can you ensure your branch is up to date?

> Apache Kafka is very important to monitory end-to-end the peaces mainly the clients.

That doesn't mean we should be encouraging using JMX unnecessarily to monitor them.

**Comment by dhoard** [comment]
Closing since there are references to configuring Kafa client metrics by 3rd parties.

**Pull request closed without merging**
