### PR TITLE
Add kafka.coordinator.* metrics

### LINKED ISSUE #393: Fix kafka-2_0_0.yml to include kafka.coordinator metrics
Current sample is pretty comprehensive but misses out on `kafka.coordinator.group` and `kafka.coordinator.transaction` metrics.

### PR DESCRIPTION
**Pull request by Walliee**
Resolves #393

### CODE REVIEW

**Comment by brian-brazil** [comment]
What do the new metrics look like?

**Comment by Walliee** [comment]
I was unable to find any documentation for these (which is why they were probably missed in the first place) but here they are from the source:

**kafka.coordinator.transaction**
https://github.com/apache/kafka/blob/050fdd6537fcfb640277ff5e1607e44d18c0d95f/core/src/main/scala/kafka/coordinator/transaction/TransactionMarkerChannelManager.scala#L146-L158

**kafka.coordinator.group**
https://github.com/apache/kafka/blob/6dd4ebcea78f9c6fb8a2921cab3fd92be4978063/core/src/main/scala/kafka/coordinator/group/GroupMetadataManager.scala#L92-L137

**Comment by brian-brazil** [comment]
I meant more what does the jmx exporter expose for these now with this config?

**Comment by Walliee** [comment]
Using the current version of the config, kafka.coordinator.* are ignored as they are not captured by even the most generic pattern:
```
- pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
  name: kafka_$1_$2_$3
  type: GAUGE
```

With the new addition to the config the following gauges will be exposed:

- kafka_coordinator_group_groupmetadatamanager_numgroups
- kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance
- kafka_coordinator_group_groupmetadatamanager_numgroupsdead
- kafka_coordinator_group_groupmetadatamanager_numgroupsempty
- kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance
- kafka_coordinator_group_groupmetadatamanager_numgroupsstable
- kafka_coordinator_transaction_transactionmarkerchannelmanager_logappendretryqueuesize
- kafka_coordinator_transaction_transactionmarkerchannelmanager_unknowndestinationqueuesize

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
