### PR TITLE
Revert: "Add gzip compression on jetty (#137, #139)" to restore java 1.6 compatibility

### PR DESCRIPTION
**Pull request by erebe**
It is reverting the following
  + Gzip compression
  + Usage of ReuseAddress port for the http server
  +  bump of maven-shade plugin

This reverts commit 
e4f8280b52ac208c24ebbff4fb1be28ea0fe667d
fde351f805e46b59f85d76fcee07ffa93c83aef6

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you confirm everything is back down to 1.6 or earlier?

**Comment by erebe** [comment]
For the java agent
```
find . -name *.class -exec file -b {} \; | sort | uniq
compiled Java class data, version 49.0 (Java 1.5)
compiled Java class data, version 50.0 (Java 1.6)
```

For the the client
```
find . -name *.class -exec file -b {} \; | sort | uniq
compiled Java class data, version 49.0 (Java 1.5)
compiled Java class data, version 50.0 (Java 1.6)
```

I also tested the client with docker 6-jdk and it is working

**Comment by erebe** [comment]
gentle bump

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
