### PR TITLE
Change white/blacklist naming convention

### PR DESCRIPTION
**Pull request by richardbadman**
This is just a small PR to change the naming convention of two variables that are used within this repository, coming from a diversity and inclusion point of view, the proposed changes in this PR don't have negative racial historic connotations attached with them.

I have also tested this working on a tiny HBase cluster of 4 machines

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. Changing these names is on the cards, however it is a breaking change in a widely used tool. There is interest and someone in the community who said they were working on expanding these particular options to work on not just the object names but also the attribute names, which would also be a breaking change. Accordingly to minimise disruption to end users, I want to combine breaking changes as much as is possible, and have this altered as part of that functionality expansion rather than breaking the same config fields twice in a row.


Also I think processed/ignored would make more sense here, as we're not allowing/denying anything.

**Comment by richardbadman** [comment]
Thanks for the feedback, with that in mind, should I close this PR in favour of word going on elsewhere that someone is working on?

**Comment by brian-brazil** [comment]
Let's leave it open in case anyone else is wondering, as while it has always been the plan it wasn't written down until now.

**Comment by dhoard** [comment]
I have a draft PR https://github.com/prometheus/jmx_exporter/pull/852 in progress for this change.

Existing configurations using `whitelistObjectNames` and `blacklistObjects` will continue to work, but we should consider them deprecated.

**Comment by dhoard** [comment]
Closing. Implemented and merged changes.

**Pull request closed without merging**
