### PR TITLE
Use queryMBeans instead of queryNames.

### PR DESCRIPTION
**Pull request by icetrain**
Solves #89 

No noticable performance impact when testing scrape of a target with about 1800 MBeans.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This code should be equivalent, do you know why it's not?

**Comment by icetrain** [comment]
No I'm afraid not, my testing shows that queryMBeans finds the bean I'm looking for but queryNames is not unless I broaden the scope of the query to domain:* and then apply a filter but that's much slower than using queryMBeans.

**Comment by brian-brazil** [comment]
Very odd, can you add a comment pointing to this issue so it doesn't get accidentally reverted in the future?

**Comment by icetrain** [comment]
Updated with comment pointing to #89

**Pull request merged**
