### PR TITLE
Clean up examples

### PR DESCRIPTION
**Pull request by preisbeck**
Hi Brian,

while testing the exporter with our Zookeeper setup I noticed that the patterns won't match properly if they are not quoted. So I adjusted all examples a bit to include double quotes around the Names, Patterns and Label Values, plus some minor consistency fixes.
Hope this helps somehow.

kind regards,
Phillip Reisbeck

### CODE REVIEW

**Comment by brian-brazil** [comment]
That's a bit odd, we haven't ever changed the YAML library we use or it's version.

**Comment by preisbeck** [comment]
Hey Brian,

thanks for taking a look at my PR. I just verified the behavior on our QA machine.

```
:~# cat /etc/jmx_exporter/zookeeper.yaml 
startDelaySeconds: 0
rules:
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
    name: "zookeeper_$2"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
    name: "zookeeper_$3"
    labels:
      replicaId: "$2"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
    name: "zookeeper_$4"
    labels:
      replicaId: "$2"
      memberType: "$3"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
    name: "zookeeper_$4_$5"
    labels:
      replicaId: "$2"
      memberType: "$3"`

```

gives me following metrics:


```
:~# curl -Ss localhost:9111 | grep ^zoo | awk '{print $1}'
zookeeper_MaxClientCnxnsPerHost{memberType="Follower",replicaId="1",}
zookeeper_MaxClientCnxnsPerHost{replicaId="1",}
zookeeper_MaxSessionTimeout{memberType="Follower",replicaId="1",}
zookeeper_MaxSessionTimeout{replicaId="1",}
zookeeper_ElectionTimeTaken{memberType="Follower",replicaId="1",}
zookeeper_MaxRequestLatency{memberType="Follower",replicaId="1",}
zookeeper_ElectionType{replicaId="1",}
zookeeper_PendingRevalidationCount{memberType="Follower",replicaId="1",}
zookeeper_PacketsReceived{memberType="Follower",replicaId="1",}
zookeeper_SyncLimit{replicaId="1",}
zookeeper_Tick{replicaId="1",}
zookeeper_MinRequestLatency{memberType="Follower",replicaId="1",}
zookeeper_TickTime{memberType="Follower",replicaId="1",}
zookeeper_TickTime{replicaId="1",}
zookeeper_NumAliveConnections{memberType="Follower",replicaId="1",}
zookeeper_InitLimit{replicaId="1",}
zookeeper_PacketsSent{memberType="Follower",replicaId="1",}
zookeeper_InMemoryDataTree_NodeCount{memberType="Follower",replicaId="1",}
zookeeper_MinSessionTimeout{memberType="Follower",replicaId="1",}
zookeeper_MinSessionTimeout{replicaId="1",}
zookeeper_OutstandingRequests{memberType="Follower",replicaId="1",}
zookeeper_AvgRequestLatency{memberType="Follower",replicaId="1",}
zookeeper_InMemoryDataTree_WatchCount{memberType="Follower",replicaId="1",}
zookeeper_QuorumSize
```


After unquoting the patterns I only get jvm standard metrics. We currently use zookeeper in version 3.4.10-2 on the following setup:

```
~# uname -a
Linux qa-kafka 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux
```

```
~# java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

```

I'll try to investigate the problem further.

**Comment by brian-brazil** [comment]
Did you manage to figure out what's going on?

**Comment by preisbeck** [comment]
No actually I couldn't replicate this, even more not for all the documentation I changed. As most of the files got changed since I looked in to this, and there are some conflicts now, I'll close my PR.

**Pull request closed without merging**
