### PR TITLE
suppport multiple instances for one http server

### PR DESCRIPTION
**Pull request by WillCup**
As title....

Cannot find your code style. So, please reformat the code

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. The Prometheus architecture is to have one exporter per instance, and for the jmx exporter it's to use an agent per instance. Thus this change is not in line with how we do things. In addition things like the instance name would belong as a label rather than part of the metric name.

**Comment by WillCup** [comment]
Got it. But I am wondering why not manager + plugins for exporter part?

Could you give me a related link? Hope can get new vision.

Thanks very much!

**Comment by brian-brazil** [comment]
https://www.robustperception.io/one-agent-to-rule-them-all/

**Comment by WillCup** [comment]
As the article said, exporters should be grouped by service, but not by instance. 

For example, a kafka service may has 5 or 7 server instances, I think they should be monitored  as one service.

Then, one exporter manager to one service. Each exporter should has the same JMX metric regex, but with different 'instance' label for each metric.

**Comment by brian-brazil** [comment]
You run one jmx exporter per instance, aggregation per service would be done up in Prometheus.

**Comment by WillCup** [comment]
Ok. But all metrics require tow labels: instance and service, those labels can help Prometheus figure out where exactly all the same name metrics come from. 

`
kafka_metric1{service='kafka', instance='node1', xx=yy}  123

kafka_metric1{service='kafka', instance='node2', xx=yy}  123
`

not

`
kafka_metric1{xx=yy}  123

kafka_metric1{xx=yy}  123
`

It is necessary for alter message.

Right?

**Comment by brian-brazil** [comment]
This is all handled by Prometheus.

**Comment by WillCup** [comment]
How?

I am using the httpserver.

Metric samples from export1, localhost:5555/metrics:

`
kafka_network_requestmetrics_totaltimems{request="GroupCoordinator",} 18.0
kafka_network_requestmetrics_totaltimems{request="OffsetFetch",} 9.0
kafka_network_requestmetrics_totaltimems{request="JoinGroup",} 11.0
kafka_network_requestmetrics_totaltimems{request="ListGroups",} 0.0
kafka_network_requestmetrics_totaltimems{request="SyncGroup",} 11.0
kafka_network_requestmetrics_totaltimems{request="Fetch",} 1.2414207E7
...
...
`

Metric samples from export2, localhost:5556/metrics:

`
kafka_network_requestmetrics_totaltimems{request="GroupCoordinator",} 18.0
kafka_network_requestmetrics_totaltimems{request="OffsetFetch",} 9.0
kafka_network_requestmetrics_totaltimems{request="JoinGroup",} 11.0
kafka_network_requestmetrics_totaltimems{request="ListGroups",} 0.0
kafka_network_requestmetrics_totaltimems{request="SyncGroup",} 11.0
kafka_network_requestmetrics_totaltimems{request="Fetch",} 1.2414207E7
...
...
`

Prometheus server has tow targets: localhost:5555/metrics, locahost:5556/metrics.

How can Prometheus figure out where exactly a `kafka_network_requestmetrics_totaltimems{request="SyncGroup",} 11.0 
`  message come from?

Help, please

**Comment by brian-brazil** [comment]
This is getting into general usage questions, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue.

**Comment by WillCup** [comment]
Sorry, and Thank you.

**Pull request closed without merging**
